<?php

$root = dirname(__DIR__);

$manager = file_get_contents($root . '/src/Services/DigitalServiceManager.php');
$index = file_get_contents($root . '/index.php');
$admin = file_get_contents($root . '/admin.php');
$keyboard = file_get_contents($root . '/keyboard.php');
$setting = file_get_contents($root . '/db/tables/setting.php');
$panel = file_get_contents($root . '/panel/digital_services.php');
$servicePanel = file_get_contents($root . '/panel/service.php');
$invoicePanel = file_get_contents($root . '/panel/invoice.php');
$categoryPanel = file_get_contents($root . '/panel/category.php');
$categoryTable = file_get_contents($root . '/db/tables/digital_service_categories.php');
$tgTools = file_get_contents($root . '/src/Services/TgToolsClient.php');
$ozvinooClient = file_get_contents($root . '/src/Services/OZVinooClient.php');
$smmClient = file_get_contents($root . '/src/Services/SmmPanelClient.php');
$nobitexClient = file_get_contents($root . '/src/Services/NobitexMarketClient.php');
$providerCatalog = file_get_contents($root . '/src/Services/DigitalServiceProviderCatalog.php');
$providerTable = file_get_contents($root . '/db/tables/digital_service_providers.php');
$cronJobs = file_get_contents($root . '/cronbot/jobs.php');
$digitalServicesCron = file_get_contents($root . '/cronbot/digital_services.php');
$settings = file_get_contents($root . '/db/tables/digital_service_settings.php');
$langFa = file_get_contents($root . '/lang/fa.php');

$buyStart = strpos($index, "} elseif (preg_match('/^ds_buy:");
$buyEnd = $buyStart === false
    ? false
    : strpos($index, "} elseif (\$user['step'] === 'digital_service_target')", $buyStart);
$buyRoute = ($buyStart !== false && $buyEnd !== false)
    ? substr($index, $buyStart, $buyEnd - $buyStart)
    : '';

$checks = [
    [str_contains($manager, "providerSupportsAutomaticDelivery"), 'provider automatic-delivery capability check missing'],
    [str_contains($manager, "providerApprovalMode"), 'per-provider approval mode reader missing'],
    [str_contains($manager, "setProviderApprovalMode"), 'per-provider approval mode writer missing'],
    [str_contains($manager, "provider_approval_"), 'provider approval mode storage key missing'],
    [str_contains($manager, "maybeAutoApproveOrder"), 'automatic order approval dispatcher missing'],
    [str_contains($manager, "admin_id = ?"), 'automatic delivery must reuse atomic approval claim'],
    [str_contains($manager, "deliverRegisteredSmmProvider"), 'generic SMM provider delivery adapter missing'],
    [str_contains($manager, "reconcileRegisteredSmmProcessing"), 'generic SMM provider reconciliation missing'],
    [str_contains($index, "maybeAutoApproveOrder"), 'bot checkout must attempt automatic provider delivery'],
    [str_contains($index, "$automaticHandled"), 'bot checkout automatic-delivery guard missing'],
    [str_contains($digitalServicesCron, "reconcileRegisteredSmmProcessing"), 'generic SMM reconciliation cron missing'],
    [str_contains($panel, 'name="tgtools_approval_mode"'), 'TGTools approval-mode selector missing'],
    [str_contains($panel, 'name="ozvinoo_approval_mode"'), 'OZVinoo approval-mode selector missing'],
    [str_contains($panel, 'name="tivanovin_approval_mode"'), 'TivaNovin approval-mode selector missing'],
    [str_contains($panel, 'name="provider_approval_mode"'), 'generic provider approval-mode selector missing'],
    [str_contains($panel, "set_provider_approval_mode"), 'generic provider approval-mode action missing'],
    [str_contains($providerCatalog, "DELETE FROM digital_service_settings WHERE setting_key = ?"), 'provider approval mode cleanup missing'],
    [str_contains($smmClient, "final class SmmPanelClient"), 'generic SMM panel client missing'],
    [str_contains($smmClient, "['action' => 'services']"), 'SMM services request missing'],
    [str_contains($smmClient, "'action' => 'add'"), 'SMM add-order request missing'],
    [str_contains($smmClient, "'action' => 'status'"), 'SMM order-status request missing'],
    [str_contains($smmClient, "['action' => 'balance']"), 'SMM balance request missing'],
    [str_contains($smmClient, "tivanovin.ir"), 'TivaNovin legacy endpoint allowlist missing'],
    [str_contains($smmClient, "CURLOPT_FOLLOWLOCATION => false"), 'SMM API must not follow redirects with credentials'],
    [str_contains($providerCatalog, "isSafeTivaNovinLegacyUrl"), 'TivaNovin catalog legacy HTTP guard missing'],
    [str_contains($providerCatalog, "['ozvinoo', 'tivanovin']"), 'TivaNovin catalog products must use integrated delivery metadata'],
    [str_contains($manager, "saveTivaNovinProvider"), 'TivaNovin provider bootstrap missing'],
    [str_contains($manager, "tivaNovinWalletStatus"), 'TivaNovin wallet diagnostics missing'],
    [str_contains($manager, "provider === 'tivanovin'"), 'TivaNovin provider dispatch missing'],
    [str_contains($manager, "deliverTivaNovin"), 'TivaNovin delivery adapter missing'],
    [str_contains($manager, "reconcileTivaNovinProcessing"), 'TivaNovin order reconciliation missing'],
    [str_contains($manager, "'smm:.'"), 'TivaNovin fixed SMM service mapping missing'],
    [str_contains($manager, "'rial', 0.1"), 'TivaNovin IRR-to-Toman pricing conversion missing'],
    [str_contains($panel, "save_tivanovin"), 'TivaNovin admin settings action missing'],
    [str_contains($panel, "sync_tivanovin_catalog"), 'TivaNovin manual catalog sync action missing'],
    [str_contains($panel, "TivaNovin / تیوا نوین"), 'TivaNovin admin card missing'],
    [str_contains($panel, "کیف پول API تیوا نوین"), 'TivaNovin wallet UI missing'],
    [str_contains($digitalServicesCron, "reconcileTivaNovinProcessing"), 'TivaNovin reconciliation cron missing'],
    [str_contains($providerCatalog, "syncDueProviders"), 'provider catalog scheduler missing'],
    [str_contains($providerCatalog, "syncProvider"), 'provider catalog synchronizer missing'],
    [str_contains($providerCatalog, "normaliseCategory"), 'provider automatic categorisation missing'],
    [str_contains($providerCatalog, "'youtube' =>"), 'YouTube category mapping missing'],
    [str_contains($providerCatalog, "'twitter' =>"), 'Twitter/X category mapping missing'],
    [str_contains($providerCatalog, "'tiktok' =>"), 'TikTok category mapping missing'],
    [str_contains($providerCatalog, "'spotify' =>"), 'Spotify category mapping missing'],
    [str_contains($providerCatalog, "'linkedin' =>"), 'LinkedIn category mapping missing'],
    [str_contains($providerCatalog, "'facebook' =>"), 'Facebook category mapping missing'],
    [str_contains($providerCatalog, "calculateSellingPrice"), 'provider automatic profit pricing missing'],
    [str_contains($providerCatalog, "FILTER_FLAG_NO_PRIV_RANGE"), 'provider catalog SSRF private-range guard missing'],
    [str_contains($providerCatalog, "CURLOPT_PROTOCOLS => CURLPROTO_HTTPS"), 'provider catalog must be HTTPS-only'],
    [str_contains($providerCatalog, "disableMissingProducts"), 'provider removed products must be auto-disabled'],
    [str_contains($providerCatalog, "discoverCatalogUrl"), 'provider catalog endpoint discovery missing'],
    [str_contains($providerCatalog, "autoDiscoverCatalogMapping"), 'provider catalog field auto-detection missing'],
    [str_contains($providerCatalog, "normaliseItemCollection"), 'provider associative catalog normalization missing'],
    [str_contains($providerCatalog, "requestSmmServices"), 'SMM POST catalog support missing'],
    [str_contains($providerCatalog, "DISCOVERY_MAX_ATTEMPTS"), 'provider discovery request budget missing'],
    [str_contains($providerCatalog, "DISCOVERY_BUDGET_SECONDS"), 'provider discovery time budget missing'],
    [str_contains($providerCatalog, "DISCOVERY_REQUEST_TIMEOUT_SECONDS"), 'provider discovery request timeout missing'],
    [str_contains($providerCatalog, "CURLINFO_REDIRECT_URL"), 'provider safe redirect detection missing'],
    [str_contains($providerCatalog, "$sourceHost === $redirectHost"), 'provider redirects must stay on the same host'],
    [str_contains($providerCatalog, "['/api/', '/api/v2/'"), 'canonical trailing-slash API candidates missing'],
    [str_contains($providerCatalog, "hostSafetyCache"), 'provider host safety DNS cache missing'],
    [str_contains($providerCatalog, "discoverLinkedApiEndpoints"), 'API-root linked endpoint discovery missing'],
    [str_contains($providerCatalog, "diagnosticTopLevelKeys"), 'API-root diagnostic key reporting missing'],
    [str_contains($providerCatalog, "GET/discovered"), 'linked catalog probe flow missing'],
    [str_contains($providerCatalog, "authProfiles"), 'multi-auth provider discovery missing'],
    [str_contains($providerCatalog, "$authHeader !== '' && !preg_match"), 'body-only provider auth header must be allowed'],
    [str_contains($providerCatalog, "X-API-Key"), 'X-API-Key discovery profile missing'],
    [str_contains($providerCatalog, "collectArrayPaths"), 'recursive JSON catalog discovery missing'],
    [str_contains($providerCatalog, "'action' => 'services'"), 'SMM services action missing'],
    [str_contains($providerCatalog, "'smm:'"), 'SMM catalog style marker missing'],
    [str_contains($providerCatalog, "wholesale_rate_per_1000"), 'SMM per-1000 rate handling missing'],
    [str_contains($providerTable, "profit_percent"), 'provider registry profit column missing'],
    [str_contains($providerTable, "exchange_rate_toman"), 'provider registry exchange-rate column missing'],
    [str_contains($manager, "pending_approval"), 'orders must enter pending approval'],
    [str_contains($manager, "approveAndDeliver"), 'manual approval delivery action missing'],
    [str_contains($manager, "rejectAndRefund"), 'reject/refund action missing'],
    [str_contains($manager, "UPDATE user SET Balance = Balance + ?"), 'refund must credit wallet'],
    [str_contains($manager, "giftPremiumSubscription"), 'Telegram Premium provider missing'],
    [str_contains($manager, "provider === 'tgtools'"), 'TGTools provider dispatch missing'],
    [str_contains($manager, "generatedProviderProductCode"), 'automatic provider product code generation missing'],
    [str_contains($manager, "categoryKeyboard"), 'digital service category keyboard missing'],
    [str_contains($manager, "virtualNumberApplications"), 'Callinoo application-level number navigation missing'],
    [str_contains($manager, "OZVINOO_CATALOG_SCHEMA_VERSION"), 'Callinoo catalog schema version missing'],
    [str_contains($manager, "ozvinoo_catalog_schema_version"), 'Callinoo catalog migration marker missing'],
    [str_contains($manager, "\$requiresCatalogMigration"), 'Callinoo forced migration freshness bypass missing'],
    [str_contains($manager, "\$applicationCatalogReady"), 'Callinoo application catalog readiness guard missing'],
    [str_contains($settings, "ozvinoo_catalog_schema_version"), 'Callinoo catalog schema setting seed missing'],
    [str_contains($manager, "virtualNumberApplicationsKeyboard"), 'Callinoo application keyboard missing'],
    [str_contains($manager, "virtualNumberApplicationCatalog"), 'Callinoo country pagination missing'],
    [str_contains($manager, "array_chunk(\$buttons, 2)"), 'Callinoo application keyboard must remain compact'],
    [str_contains($manager, "'callback_data' => 'ds_vn_app:'"), 'Callinoo application callback route missing'],
    [str_contains($manager, "ensureMainKeyboardButton"), 'upgraded-install keyboard bootstrap missing'],
    [str_contains($manager, "digital_services_keyboard_initialized"), 'keyboard bootstrap marker missing'],
    [str_contains($manager, "mainKeyboardHasDigitalServices"), 'digital-service keyboard status helper missing'],
    [str_contains($manager, "categoryForProduct"), 'digital service category mapping missing'],
    [str_contains($manager, "if (\$type === 'telegram_premium')"), 'Telegram Premium category mapping missing'],
    [str_contains($manager, "if (\$type === 'telegram_stars')"), 'Telegram Stars category mapping missing'],
    [str_contains($manager, "ensureTgToolsCatalog"), 'automatic Stars/Premium catalog generation missing'],
    [str_contains($manager, "refreshTgToolsTonRateFromNobitex"), 'live Nobitex TON-rate refresh missing'],
    [str_contains($manager, "repriceTgToolsCatalogFromTonRate"), 'TGTools repricing after TON-rate changes missing'],
    [str_contains($manager, "'ton_rate_source' => 'nobitex'"), 'TGTools product metadata must record Nobitex as TON-rate source'],
    [str_contains($manager, "'ton_rate_market' => 'GRAMIRT'"), 'TGTools product metadata must record GRAMIRT market'],
    [str_contains($manager, "tgToolsLandedTonRate"), 'TGTools landed GRAM cost calculation missing'],
    [str_contains($manager, "tgtools_nobitex_trade_fee_percent"), 'Nobitex trade fee setting missing'],
    [str_contains($manager, "refreshTgToolsNobitexWithdrawalFee"), 'Nobitex GRAM withdrawal-fee refresh missing'],
    [str_contains($manager, "tgtools_nobitex_withdraw_fee_gram"), 'Nobitex GRAM withdrawal fee setting missing'],
    [str_contains($nobitexClient, "gramWithdrawalInfo"), 'Nobitex public GRAM withdrawal info client missing'],
    [str_contains($nobitexClient, "/v2/options"), 'Nobitex public options endpoint missing'],
    [str_contains($nobitexClient, "withdrawFee"), 'Nobitex GRAM withdrawFee parser missing'],
    [str_contains($panel, "کارمزد برداشت GRAM از نوبیتکس"), 'Nobitex GRAM withdrawal fee must be visible in panel'],
    [str_contains($manager, "tgtools_gram_network_fee"), 'GRAM network fee setting missing'],
    [str_contains($manager, "tgtools_gram_funding_batch"), 'TGTools funding batch allocation setting missing'],
    [str_contains($panel, "نرخ تمام‌شده GRAM برای TGTools"), 'landed GRAM rate must be visible in panel'],
    [str_contains($nobitexClient, "/v3/orderbook/"), 'Nobitex orderbook endpoint missing'],
    [str_contains($nobitexClient, "https://apiv2.nobitex.ir"), 'Nobitex client must use the documented apiv2 host'],
    [str_contains($nobitexClient, "Nobitex-Key:"), 'Nobitex signed API key public header missing'],
    [str_contains($nobitexClient, "Nobitex-Signature:"), 'Nobitex signed API key signature header missing'],
    [str_contains($nobitexClient, "Nobitex-Timestamp:"), 'Nobitex signed API key timestamp header missing'],
    [str_contains($nobitexClient, "sodium_crypto_sign_detached"), 'Nobitex Ed25519 signing support missing'],
    [str_contains($nobitexClient, "return strtr(base64_encode(\$value), '+/', '-_');"), 'Nobitex URL-safe Base64 signature must preserve padding'],
    [!str_contains($nobitexClient, "rtrim(strtr(base64_encode(\$value), '+/', '-_'), '=')"), 'Nobitex signature padding must not be stripped'],
    [str_contains($nobitexClient, "/users/profile"), 'Nobitex API key validation endpoint missing'],
    [str_contains($manager, "testNobitexApiKey"), 'Nobitex API key test bridge missing'],
    [str_contains($panel, "Nobitex Public Key"), 'Nobitex Public Key panel input missing'],
    [str_contains($panel, "Nobitex Private Key"), 'Nobitex Private Key panel input missing'],
    [str_contains($panel, "test_nobitex_api_key"), 'Nobitex API key test action missing'],
    [str_contains($settings, "nobitex_api_public_key"), 'Nobitex public API key setting seed missing'],
    [str_contains($settings, "nobitex_api_private_key"), 'Nobitex private API key setting seed missing'],
    [str_contains($nobitexClient, "GRAMIRT"), 'Nobitex GRAMIRT market missing'],
    [str_contains($nobitexClient, "lastTradePrice"), 'Nobitex lastTradePrice parser missing'],
    [str_contains($nobitexClient, "RIALS_PER_TOMAN"), 'Nobitex rial-to-toman conversion constant missing'],
    [str_contains($nobitexClient, "raw_rate_rial"), 'Nobitex raw rial quote diagnostics missing'],
    [str_contains($nobitexClient, "/ self::RIALS_PER_TOMAN"), 'Nobitex GRAM rate must be converted from rial to toman'],
    [str_contains($digitalServicesCron, "refreshTgToolsTonRateFromNobitex"), 'cron must refresh Nobitex TON rate'],
    [str_contains($panel, "دریافت نرخ لحظه‌ای نوبیتکس"), 'manual Nobitex TON-rate refresh control missing'],
    [!str_contains($panel, 'name="tgtools_ton_toman_rate"'), 'manual TON-rate input must be removed'],
    [str_contains($manager, "WHERE provider = 'tgtools' AND type = ? AND service_value = ?"), 'TGTools catalog must not hijack matching products from other providers'],
    [str_contains($manager, "maybeSyncTgToolsCatalog"), 'periodic TGTools catalog refresh missing'],
    [str_contains($manager, "tgToolsWalletStatus"), 'TGTools API wallet diagnostics missing'],
    [str_contains($manager, "TGTOOLS_WALLET_INSUFFICIENT"), 'TGTools insufficient-wallet classification missing'],
    [str_contains($manager, "markRetryableProviderFailure"), 'retryable provider failure state missing'],
    [str_contains($manager, "maybeBootstrapOZVinooCatalog"), 'existing OZVinoo auto-bootstrap missing'],
    [str_contains($manager, "syncOZVinooCatalog"), 'official OZVinoo catalog synchronization missing'],
    [str_contains($manager, "ozvinooWalletStatus"), 'OZVinoo wallet diagnostics missing'],
    [str_contains($manager, "reconcileOZVinooProcessing"), 'OZVinoo async reconciliation missing'],
    [str_contains($manager, "deliverOZVinooOfficial"), 'OZVinoo official delivery adapter missing'],
    [str_contains($manager, "presetTarget"), 'OZVinoo virtual-number preset target missing'],
    [str_contains($manager, "ozvinoo_api_style"), 'OZVinoo API style persistence missing'],
    [str_contains($manager, "'youtube' => '▶️ خدمات یوتیوب'"), 'customer YouTube category label missing'],
    [str_contains($manager, "'tiktok' => '🎵 خدمات تیک‌تاک'"), 'customer TikTok category label missing'],
    [str_contains($manager, "deliverOZVinooSmm"), 'OZVinoo SMM order delivery missing'],
    [str_contains($manager, "'action' => 'add'"), 'OZVinoo SMM add-order action missing'],
    [str_contains($manager, "tgtools_stars_profit_percent"), 'TGTools Stars margin setting missing'],
    [str_contains($manager, "tgtools_premium_profit_percent"), 'TGTools Premium margin setting missing'],
    [str_contains($manager, "tgtools_ton_toman_rate"), 'TGTools TON-to-Toman rate setting missing'],
    [str_contains($manager, "calculateSellingPrice"), 'TGTools automatic margin pricing missing'],
    [str_contains($manager, "category_label"), 'dynamic provider category labels missing'],
    [str_contains($manager, "targetKeyboard"), 'dedicated inline target keyboard missing'],
    [str_contains($manager, "ORDER_STATE_INVALID"), 'order confirmation idempotency guard missing'],
    [str_contains($manager, "digital_service_processing"), 'atomic order-intent claim missing'],
    [str_contains($manager, "SELECT * FROM user WHERE id = ? FOR UPDATE"), 'user order-intent row lock missing'],
    [str_contains($manager, "provider_service_code = NULL"), 'TGTools products must not require provider service codes'],
    [str_contains($manager, "reconcileTgToolsProcessing"), 'TGTools async reconciliation missing'],
    [str_contains($manager, "failAndRefundProviderOrder"), 'TGTools provider failure refund missing'],
    [substr_count($manager, "failAndRefundProviderOrder(") >= 4, 'all provider delivery failure paths must refund automatically'],
    [str_contains($tgTools, "https://api.tg-tools.shop"), 'TGTools host allowlist missing'],
    [str_contains($tgTools, "/api/purchase/stars"), 'TGTools Stars endpoint missing'],
    [str_contains($tgTools, "/api/purchase/premium"), 'TGTools Premium endpoint missing'],
    [str_contains($tgTools, "/api/purchase/prices"), 'TGTools live prices endpoint missing'],
    [str_contains($tgTools, "/api/wallet"), 'TGTools API wallet endpoint missing'],
    [str_contains($tgTools, "/api/transaction/"), 'TGTools documented transaction status endpoint missing'],
    [str_contains($tgTools, "X-Api-Key"), 'TGTools API key authentication missing'],
    [str_contains($tgTools, "trackingCode"), 'TGTools idempotency tracking code missing'],
    [str_contains($cronJobs, "'job' => 'digital_services'"), 'TGTools reconciliation cron is not scheduled'],
    [str_contains($digitalServicesCron, "maybeSyncTgToolsCatalog"), 'TGTools live catalog cron refresh missing'],
    [str_contains($digitalServicesCron, "syncDueProviders"), 'generic provider catalog cron sync missing'],
    [str_contains($digitalServicesCron, "maybeBootstrapOZVinooCatalog"), 'OZVinoo cron catalog sync missing'],
    [str_contains($digitalServicesCron, "reconcileOZVinooProcessing"), 'OZVinoo order reconciliation cron missing'],
    [str_contains($settings, "tgtools_api_key"), 'TGTools API key setting missing'],
    [str_contains($settings, "tgtools_catalog_last_sync"), 'TGTools catalog sync timestamp setting missing'],
    [str_contains($settings, "tgtools_stars_profit_percent"), 'TGTools Stars profit seed missing'],
    [str_contains($settings, "tgtools_premium_profit_percent"), 'TGTools Premium profit seed missing'],
    [str_contains($settings, "tgtools_ton_toman_rate"), 'TGTools TON rate seed missing'],
    [str_contains($settings, "tgtools_ton_rate_source"), 'Nobitex rate source seed missing'],
    [str_contains($settings, "tgtools_ton_rate_market"), 'Nobitex market seed missing'],
    [str_contains($settings, "tgtools_ton_rate_last_sync"), 'Nobitex rate sync timestamp seed missing'],
    [str_contains($settings, "ozvinoo_profit_percent"), 'OZVinoo profit seed missing'],
    [str_contains($settings, "ozvinoo_catalog_path"), 'OZVinoo catalog path seed missing'],
    [str_contains($settings, "ozvinoo_exchange_rate_toman"), 'OZVinoo exchange rate seed missing'],
    [str_contains($settings, "ozvinoo_api_style"), 'OZVinoo API style seed missing'],
    [str_contains($settings, "ozvinoo_catalog_last_sync"), 'OZVinoo catalog sync timestamp setting missing'],
    [str_contains($settings, "digital_services_keyboard_initialized"), 'digital-service keyboard bootstrap setting missing'],
    [str_contains($panel, "save_tgtools"), 'TGTools admin settings UI missing'],
    [!str_contains($panel, "SET provider = 'tgtools'"), 'TGTools settings must not rewrite products owned by other providers'],
    [str_contains($panel, "sync_tgtools_catalog"), 'TGTools catalog sync action missing'],
    [str_contains($panel, "save_provider_catalog"), 'generic provider catalog save action missing'],
    [str_contains($panel, "sync_provider_catalog"), 'generic provider manual sync action missing'],
    [str_contains($panel, "profit_percent"), 'provider profit percentage UI missing'],
    [str_contains($panel, "tgtools_stars_profit_percent"), 'TGTools Stars separate margin UI missing'],
    [str_contains($panel, "tgtools_premium_profit_percent"), 'TGTools Premium separate margin UI missing'],
    [str_contains($panel, "ozvinoo_profit_percent"), 'OZVinoo provider-wide profit UI missing'],
    [str_contains($panel, "کیف پول API TGTools"), 'TGTools API wallet balance UI missing'],
    [str_contains($panel, "موجودی TGTools"), 'TGTools wallet balance field missing'],
    [str_contains($panel, "آدرس کیف پول / واریز TGTools"), 'TGTools wallet address field missing'],
    [str_contains($panel, "data-copy-tgtools-wallet"), 'TGTools wallet copy control missing'],
    [str_contains($panel, "محصولات فعال عضوینو در ربات"), 'OZVinoo product-sync diagnostics missing'],
    [str_contains($panel, "sync_ozvinoo_catalog"), 'OZVinoo catalog sync action missing'],
    [str_contains($panel, "syncOZVinooCatalog"), 'OZVinoo panel must use official catalog sync'],
    [str_contains($panel, "کیف پول API عضوینو"), 'OZVinoo wallet balance UI missing'],
    [str_contains($panel, "API رسمی"), 'OZVinoo official API UI copy missing'],
    [str_contains($panel, "data-ozvinoo-sync-form"), 'OZVinoo official sync progress guard missing'],
    [str_contains($panel, "مدیریت APIها"), 'Digital Services settings page purpose copy missing'],
    [!str_contains($panel, '<div class="card-title">سرویس‌ها</div>'), 'service list leaked back into API settings page'],
    [!str_contains($panel, '<div class="card-title">سفارش‌ها</div>'), 'order list leaked back into API settings page'],
    [str_contains($panel, "products_path' => \$_POST['products_path'] ?? 'auto'"), 'generic provider mapping must default to auto'],
    [str_contains($servicePanel, "digital_add"), 'digital service create action must live under Services'],
    [str_contains($servicePanel, "digital_edit"), 'digital service edit action must live under Services'],
    [str_contains($servicePanel, "digital_toggle"), 'digital service activation action must live under Services'],
    [str_contains($servicePanel, "digital_delete"), 'digital service delete action must live under Services'],
    [str_contains($servicePanel, "scope=digital"), 'Services digital scope missing'],
    [str_contains($servicePanel, "'tgtools'"), 'TGTools provider support missing from Services digital scope'],
    [str_contains($invoicePanel, "digital_approve"), 'digital order approval must live under Orders'],
    [str_contains($invoicePanel, "digital_reject"), 'digital order rejection must live under Orders'],
    [str_contains($invoicePanel, "scope=digital"), 'Orders digital scope missing'],
    [str_contains($categoryPanel, "digital_category_add"), 'digital category create action missing'],
    [str_contains($categoryPanel, "digital_category_edit"), 'digital category edit action missing'],
    [str_contains($categoryPanel, "digital_category_delete"), 'digital category delete action missing'],
    [str_contains($categoryPanel, "scope=digital"), 'Categories digital scope missing'],
    [str_contains($categoryTable, "category_key"), 'managed digital category table missing'],
    [str_contains($categoryTable, "virtual_number"), 'virtual-number category seed missing'],
    [str_contains($manager, "ensureManagedCategorySchema"), 'managed category self-healing schema missing'],
    [str_contains($manager, "updateProductCategory"), 'product category management API missing'],
    [str_contains($manager, "setProductAdminDisabled"), 'manual product disable persistence missing'],
    [str_contains($manager, "productAdminDisabled"), 'manual product disable reader missing'],
    [str_contains($manager, "mergeAdminProductMetadata"), 'provider sync metadata merge missing'],
    [str_contains($manager, "providerManagedActive"), 'provider sync active-state guard missing'],
    [str_contains($servicePanel, "setProductAdminDisabled"), 'Services toggle must persist manual disabled state'],
    [str_contains($servicePanel, "admin_disabled"), 'Services editor must persist manual disabled metadata'],
    [str_contains($manager, "self::providerManagedActive(\$existing, 1)"), 'OZVinoo sync must respect manual disabled state'],
    [str_contains($manager, "self::providerManagedActive(\$row, \$providerActive)"), 'TGTools sync must respect manual disabled state'],
    [str_contains($providerCatalog, "BluebotDigitalServices::providerManagedActive(\$row, 1)"), 'generic provider sync must respect manual disabled state'],
    [!str_contains($providerCatalog, "metadata = ?, active = 1, sort_order"), 'generic provider sync must not force-enable existing products'],
    [!str_contains($manager, "metadata = ?, active = 1,\n                 sort_order"), 'OZVinoo sync must not force-enable existing products'],
    [!str_contains($panel, "add_product"), 'Digital Services settings page must not manage products'],
    [!str_contains($panel, "approve_order"), 'Digital Services settings page must not approve orders'],
    [str_contains($panel, "service.php?scope=digital"), 'Digital Services page must link to Services management'],
    [str_contains($panel, "invoice.php?scope=digital"), 'Digital Services page must link to Orders management'],
    [str_contains($panel, "category.php?scope=digital"), 'Digital Services page must link to Categories management'],
    [str_contains($ozvinooClient, "https://api.ozvinoo.xyz"), 'OZVinoo host allowlist missing'],
    [str_contains($ozvinooClient, "CURLOPT_PROTOCOLS => CURLPROTO_HTTPS"), 'OZVinoo must be HTTPS-only'],
    [str_contains($ozvinooClient, "/web/") && str_contains($ozvinooClient, "/get-balance"), 'OZVinoo balance endpoint missing'],
    [str_contains($ozvinooClient, "/telegram-services/stars/"), 'OZVinoo Stars endpoint missing'],
    [str_contains($ozvinooClient, "/telegram-services/premium/"), 'OZVinoo Premium endpoint missing'],
    [str_contains($ozvinooClient, "/telegram-services/status/"), 'OZVinoo Telegram order status endpoint missing'],
    [str_contains($ozvinooClient, "/telegram-numbers/numbers/"), 'OZVinoo numbers endpoint missing'],
    [str_contains($ozvinooClient, "/telegram-numbers/number-services/"), 'OZVinoo number status endpoint missing'],
    [str_contains($ozvinooClient, "/applications"), 'OZVinoo V1 applications fallback missing'],
    [str_contains($ozvinooClient, "public function applications(string \$method = 'GET')"), 'OZVinoo applications endpoint must support documented GET/POST methods'],
    [str_contains($ozvinooClient, "public function prices(int \$serviceId, string \$method = 'GET')"), 'OZVinoo prices endpoint must support documented GET/POST methods'],
    [str_contains($ozvinooClient, "/get-prices/"), 'OZVinoo V1 prices fallback missing'],
    [str_contains($ozvinooClient, "/getNumber/"), 'OZVinoo V1 number purchase fallback missing'],
    [str_contains($ozvinooClient, "/getCode/"), 'OZVinoo V1 number code fallback missing'],
    [str_contains($manager, "'api_family' => 'web-v1'"), 'OZVinoo V1 fallback catalog mapping missing'],
    [str_contains($manager, "getNumberV1"), 'OZVinoo V1 delivery fallback missing'],
    [str_contains($manager, "\$pricesResponse = \$client->prices(\$serviceId, 'GET');"), 'Callinoo must synchronize prices for every application'],
    [str_contains($manager, "\$pricesPostResponse = \$client->prices(\$serviceId, 'POST');"), 'Callinoo price discovery must fall back from GET to POST'],
    [str_contains($manager, "\$applicationsGetResponse = \$client->applications('GET');"), 'Callinoo application discovery must start with GET'],
    [str_contains($manager, "\$applicationsPostResponse = \$client->applications('POST');"), 'Callinoo application discovery must probe POST when GET is sparse'],
    [str_contains($manager, "\$applicationItemsById"), 'Callinoo GET/POST applications must be merged by service id'],
    [str_contains($manager, "'number_apps_get'"), 'Callinoo GET application diagnostics missing'],
    [str_contains($manager, "'number_apps_post'"), 'Callinoo POST application diagnostics missing'],
    [str_contains($panel, "GET "), 'Callinoo method diagnostics must be visible in panel'],
    [str_contains($manager, "'application_id' => \$serviceId"), 'Callinoo application metadata missing'],
    [str_contains($manager, "'application_name' => \$applicationName"), 'Callinoo application name metadata missing'],
    [!str_contains($manager, "\$telegramServiceId = 0"), 'Callinoo sync must not be limited to Telegram'],
    [str_contains($manager, "getCodeV1"), 'OZVinoo V1 reconciliation fallback missing'],
    [str_contains($ozvinooClient, "/numbers/getAllOrders/"), 'OZVinoo all-orders endpoint missing'],
    [str_contains($ozvinooClient, "/numbers/getOpenOrders/"), 'OZVinoo open-orders endpoint missing'],
    [str_contains($ozvinooClient, "/numbers/getOrder/"), 'OZVinoo get-order endpoint missing'],
    [str_contains($ozvinooClient, "/numbers/cancelOrder/"), 'OZVinoo cancel-order endpoint missing'],
    [str_contains($ozvinooClient, "Authorization: Bearer"), 'OZVinoo Bearer authentication missing'],
    [str_contains($index, "ds_confirm:"), 'user order confirmation route missing'],
    [str_contains($index, "BluebotDigitalServices::ensureMainKeyboardButton(\$pdo);"), 'digital-service keyboard bootstrap is not executed'],
    [strpos($index, "ensureMainKeyboardButton") < strpos($index, "require_once __DIR__ . '/keyboard.php';"), 'keyboard bootstrap must run before keyboard rendering'],
    [str_contains($buyRoute, "BluebotDigitalServices::targetKeyboard(\$product)"), 'order target screen must use an inline keyboard'],
    [str_contains($buyRoute, "BluebotDigitalServices::presetTarget(\$product)"), 'virtual-number checkout must skip manual target input'],
    [!str_contains($buyRoute, '\$backuser'), 'order target edit must not pass ReplyKeyboardMarkup to editMessageText'],
    [str_contains($index, "ORDER_STATE_INVALID"), 'duplicate/stale confirmation handling missing'],
    [str_contains($index, "ds_category:"), 'customer category navigation route missing'],
    [str_contains($index, "/^ds_vn_app:(\\d+):(\\d+)$/"), 'Callinoo application/country callback route missing'],
    [str_contains($index, "virtualNumberApplicationsKeyboard"), 'virtual-number category must open platform selection'],
    [str_contains($index, "virtualNumberApplicationCatalog"), 'virtual-number platform must open paginated countries'],
    [str_contains($index, "لینک، یوزرنیم یا مقصد موردنیاز این سرویس"), 'OZVinoo customer target prompt missing'],
    [str_contains($index, "مقدار این بسته"), 'OZVinoo fixed-package quantity display missing'],
    [str_contains($index, "categoryKeyboard"), 'customer category landing screen missing'],
    [str_contains($index, "notifyAdmins"), 'admin notification missing'],
    [str_contains($admin, "ds_approve:"), 'bot approval callback missing'],
    [str_contains($admin, "ds_reject:"), 'bot reject callback missing'],
    [str_contains($admin, "قابل تلاش مجدد است"), 'admin retryable provider error UX missing'],
    [str_contains($admin, "مبلغ برگشت خورد"), 'admin refunded provider error UX missing'],
    [str_contains($keyboard, "text_digital_services"), 'main keyboard mapping missing'],
    [str_contains($setting, "text_digital_services"), 'default keyboard token missing'],
    [str_contains($invoicePanel, "digital_approve"), 'web approval action missing'],
    [str_contains($invoicePanel, "digital_reject"), 'web reject action missing'],
    [!str_contains($index, "ارسال فقط بعد از تأیید دستی ادمین انجام می‌شود."), 'customer product page leaks internal approval workflow'],
    [!str_contains($index, "سفارش تا تأیید دستی ادمین ارسال نخواهد شد."), 'customer confirmation leaks internal approval workflow'],
    [!str_contains($langFa, "در صف تأیید و ارسال ادمین"), 'customer queued message leaks internal approval workflow'],
    [!str_contains($manager, "برای TGTools باید یوزرنیم"), 'customer validation leaks provider name'],
    [str_contains($langFa, "سرویس موردنظر را انتخاب کنید 👇"), 'customer catalog copy was not simplified'],
    [str_contains($langFa, "دسته‌بندی موردنظر را انتخاب کنید 👇"), 'customer category prompt missing'],
];

foreach ($checks as [$ok, $message]) {
    if (!$ok) {
        fwrite(STDERR, "Digital services contract failed: {$message}\n");
        exit(1);
    }
}

echo "Digital services contract OK.\n";
