<?php

return [
    'create' => <<<SQL
        id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        panel_code VARCHAR(100) NOT NULL DEFAULT '',
        panel_name VARCHAR(200) NOT NULL DEFAULT '',
        panel_type VARCHAR(50) NOT NULL DEFAULT '',
        external_id VARCHAR(191) NOT NULL DEFAULT '',
        username VARCHAR(191) NOT NULL DEFAULT '',
        phone VARCHAR(30) NOT NULL DEFAULT '',
        note TEXT NULL,
        status VARCHAR(50) NOT NULL DEFAULT '',
        expire_at BIGINT NOT NULL DEFAULT 0,
        data_limit BIGINT NOT NULL DEFAULT 0,
        used_traffic BIGINT NOT NULL DEFAULT 0,
        created_at_panel BIGINT NOT NULL DEFAULT 0,
        edit_at_panel BIGINT NOT NULL DEFAULT 0,
        fingerprint CHAR(64) NOT NULL DEFAULT '',
        last_seen_at BIGINT NOT NULL DEFAULT 0,
        last_notified_at BIGINT NULL,
        created_at BIGINT NOT NULL DEFAULT 0,
        updated_at BIGINT NOT NULL DEFAULT 0,
        UNIQUE KEY uniq_external_panel_user (panel_code, external_id),
        KEY idx_external_panel_username (panel_code, username),
        KEY idx_external_panel_seen (last_seen_at)
        SQL,
    'columns' => [
        ['panel_code', '', 'VARCHAR(100) NOT NULL DEFAULT \'\''],
        ['panel_name', '', 'VARCHAR(200) NOT NULL DEFAULT \'\''],
        ['panel_type', '', 'VARCHAR(50) NOT NULL DEFAULT \'\''],
        ['external_id', '', 'VARCHAR(191) NOT NULL DEFAULT \'\''],
        ['username', '', 'VARCHAR(191) NOT NULL DEFAULT \'\''],
        ['phone', '', 'VARCHAR(30) NOT NULL DEFAULT \'\''],
        ['note', null, 'TEXT NULL'],
        ['status', '', 'VARCHAR(50) NOT NULL DEFAULT \'\''],
        ['expire_at', '0', 'BIGINT NOT NULL DEFAULT 0'],
        ['data_limit', '0', 'BIGINT NOT NULL DEFAULT 0'],
        ['used_traffic', '0', 'BIGINT NOT NULL DEFAULT 0'],
        ['created_at_panel', '0', 'BIGINT NOT NULL DEFAULT 0'],
        ['edit_at_panel', '0', 'BIGINT NOT NULL DEFAULT 0'],
        ['fingerprint', '', 'CHAR(64) NOT NULL DEFAULT \'\''],
        ['last_seen_at', '0', 'BIGINT NOT NULL DEFAULT 0'],
        ['last_notified_at', null, 'BIGINT NULL'],
        ['created_at', '0', 'BIGINT NOT NULL DEFAULT 0'],
        ['updated_at', '0', 'BIGINT NOT NULL DEFAULT 0'],
    ],
];
