<?php

return [
    'create' => <<<SQL
        id TINYINT UNSIGNED PRIMARY KEY,
        provider VARCHAR(50) NOT NULL DEFAULT 'iranpayamak',
        base_url VARCHAR(500) NOT NULL DEFAULT 'https://api.iranpayamak.com/ws/v1',
        api_key_enc TEXT NULL,
        from_number VARCHAR(100) NOT NULL DEFAULT '',
        active TINYINT(1) NOT NULL DEFAULT 0,
        otp_active TINYINT(1) NOT NULL DEFAULT 0,
        otp_ttl_seconds INT NOT NULL DEFAULT 120,
        otp_resend_seconds INT NOT NULL DEFAULT 60,
        otp_max_attempts INT NOT NULL DEFAULT 5,
        reminder_days_json TEXT NULL,
        low_volume_threshold_gb INT NOT NULL DEFAULT 5,
        retry_max_attempts INT NOT NULL DEFAULT 3,
        verify_tls TINYINT(1) NOT NULL DEFAULT 1,
        last_test_ok TINYINT(1) NOT NULL DEFAULT 0,
        last_test_message TEXT NULL,
        last_test_at BIGINT NULL,
        updated_at BIGINT NULL
        SQL,
    'columns' => [
        ['provider', 'iranpayamak', 'VARCHAR(50) NOT NULL DEFAULT \'iranpayamak\''],
        ['base_url', 'https://api.iranpayamak.com/ws/v1', 'VARCHAR(500) NOT NULL'],
        ['api_key_enc', null, 'TEXT NULL'],
        ['from_number', '', 'VARCHAR(100) NOT NULL DEFAULT \'\''],
        ['active', '0', 'TINYINT(1) NOT NULL DEFAULT 0'],
        ['otp_active', '0', 'TINYINT(1) NOT NULL DEFAULT 0'],
        ['otp_ttl_seconds', '120', 'INT NOT NULL DEFAULT 120'],
        ['otp_resend_seconds', '60', 'INT NOT NULL DEFAULT 60'],
        ['otp_max_attempts', '5', 'INT NOT NULL DEFAULT 5'],
        ['reminder_days_json', '[3,2,1]', 'TEXT NULL'],
        ['low_volume_threshold_gb', '5', 'INT NOT NULL DEFAULT 5'],
        ['retry_max_attempts', '3', 'INT NOT NULL DEFAULT 3'],
        ['verify_tls', '1', 'TINYINT(1) NOT NULL DEFAULT 1'],
        ['last_test_ok', '0', 'TINYINT(1) NOT NULL DEFAULT 0'],
        ['last_test_message', null, 'TEXT NULL'],
        ['last_test_at', null, 'BIGINT NULL'],
        ['updated_at', null, 'BIGINT NULL'],
    ],
    'seed' => [[
        'id' => 1,
        'provider' => 'iranpayamak',
        'base_url' => 'https://api.iranpayamak.com/ws/v1',
        'api_key_enc' => '',
        'from_number' => '',
        'active' => 0,
        'otp_active' => 0,
        'otp_ttl_seconds' => 120,
        'otp_resend_seconds' => 60,
        'otp_max_attempts' => 5,
        'reminder_days_json' => '[3,2,1]',
        'low_volume_threshold_gb' => 5,
        'retry_max_attempts' => 3,
        'verify_tls' => 1,
        'last_test_ok' => 0,
        'last_test_message' => '',
        'last_test_at' => null,
        'updated_at' => null,
    ]],
];
