<?php

return [
    ['invoice', 'idx_invoice_id_user', '`id_user`(100)'],
    ['invoice', 'idx_invoice_username', '`username`(150)'],
    ['invoice', 'idx_invoice_status', '`Status`(100)'],
    ['invoice', 'idx_invoice_location', '`Service_location`(150)'],
    ['Payment_report', 'idx_payreport_id_user', '`id_user`(100)'],
    ['Payment_report', 'idx_payreport_id_order', '`id_order`(191)'],
    ['Payment_report', 'idx_payreport_status', '`payment_Status`(100)'],
    ['marzban_panel', 'idx_panel_name', '`name_panel`(150)'],
    ['marzban_panel', 'idx_panel_code', '`code_panel`(100)'],
    ['product', 'idx_product_code', '`code_product`(50)'],
    ['product', 'idx_product_location', '`Location`(100)'],
    ['product', 'idx_product_name_location', '`name_product`(120), `Location`(100)'],
    ['manualsell', 'idx_manualsell_codepanel', '`codepanel`(100)'],
    ['service_other', 'idx_serviceother_username', '`username`(150)'],
    ['service_other', 'idx_serviceother_type', '`type`(100)'],
    ['digital_service_products', 'idx_digital_products_active_sort', '`active`, `sort_order`, `id`'],
    ['digital_service_products', 'idx_digital_products_type_provider', '`type`(50), `provider`(50)'],
    ['digital_service_orders', 'idx_digital_orders_user_created', '`user_id`(100), `created_at`'],
    ['digital_service_orders', 'idx_digital_orders_status_created', '`status`(40), `created_at`'],
    ['digital_service_orders', 'idx_digital_orders_service', '`service_id`, `created_at`'],
    ['user', 'idx_user_affiliates', '`affiliates`'],
    ['departman', 'uniq_departman_entry', '`idsupport`(100), `name_departman`(150)', true],
    ['sms_deliveries', 'uniq_sms_dedupe', '`dedupe_key`', true],
    ['sms_deliveries', 'idx_sms_status_next', '`status`(30), `next_attempt_at`'],
    ['sms_deliveries', 'idx_sms_user_created', '`user_id`(100), `created_at`'],
    ['sms_deliveries', 'idx_sms_event', '`event_key`(80)'],
    ['sms_deliveries', 'idx_sms_invoice', '`invoice_id`(100)'],
    ['sms_otp_challenges', 'idx_sms_otp_user_created', '`user_id`(100), `created_at`'],
    ['sms_otp_challenges', 'idx_sms_otp_phone_created', '`phone`(30), `created_at`'],
];
